#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5

#define ENEMY_SPAWN_FREQUENCY 1
#define ENEMY_SPEED 100.0f
#define ENEMY_PROJECTILE_SPEED 300.0f
#define ENEMY_PROJECTILE_FREQUENCY 0.5f
#endif
